services:
  - type: web
    name: breakupdoctor-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: EX_GPT
        sync: false
      - key: BOT_KEY
        sync: false
